#!/bin/sh

picom -b
xss-lock slock &
dunst &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
[ -x ~/.fehbg ] && ~/.fehbg &
dwmblocks &

export XDG_CURRENT_DESKTOP=dwm
exec dbus-run-session dwm
