export EDITOR=nvim
export VISUAL=nvim

if [[ $- != *i* ]]
then
	return
fi

shopt -s checkwinsize
shopt -s histappend

alias dotf='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'

alias rm='rm -I'
alias ls='ls -alh --color=always'

eval "$(starship init bash)"
